# Generated by Django 5.0.4 on 2024-06-26 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_typeconge_demandeconge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('seuil_conges', models.IntegerField(default=5)),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='equipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.equipe'),
            preserve_default=False,
        ),
    ]
