# Generated by Django 5.0.4 on 2024-06-26 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_equipe_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='equipe',
        ),
    ]
