# Generated by Django 5.0.4 on 2024-06-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_employe_equipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipe',
        ),
    ]
