# Generated by Django 5.0.4 on 2024-06-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_equipe_employe_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
