# Generated by Django 5.0.4 on 2024-06-27 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_equipe_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='seuil_conges',
        ),
        migrations.AddField(
            model_name='equipe',
            name='superviseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.superviseur'),
        ),
    ]
