# Generated by Django 5.0.4 on 2024-06-27 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_equipe_seuil_conges_equipe_superviseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='superviseur',
        ),
        migrations.AddField(
            model_name='superviseur',
            name='equipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.equipe'),
        ),
    ]
