# Generated by Django 5.0.4 on 2024-06-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_equipe_superviseur_superviseur_equipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='nom',
        ),
        migrations.AddField(
            model_name='equipe',
            name='seuil_conges',
            field=models.IntegerField(default=5),
        ),
    ]
