# Generated by Django 5.0.4 on 2024-06-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_equipe_nom_equipe_seuil_conges'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
